# Generated by Django 2.1 on 2018-09-17 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(default=None, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('locality', models.CharField(max_length=30)),
                ('state', models.CharField(default='Enter State', max_length=30)),
                ('postal_code_4', models.PositiveIntegerField(null=True)),
                ('user_type', models.CharField(choices=[('Entrepreneur', 'Entrepreneur'), ('Mentor', 'Mentor'), ('Investor', 'Investor'), ('Job seeker', 'Job Seeker')], max_length=20)),
                ('activation_key', models.CharField(default=uuid.UUID('f419e350-ba73-11e8-a794-9840bb29ab05'), max_length=64, verbose_name='Activation key')),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_photo', models.FileField(default=None, null=True, upload_to='')),
                ('cover_photo', models.FileField(default=None, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
