# Generated by Django 2.1 on 2018-09-17 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('c8b1ee02-baa6-11e8-bdc6-9840bb29ab05'), max_length=64, verbose_name='Activation key'),
        ),
    ]
