# Generated by Django 2.1 on 2018-09-17 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20180917_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('9f166992-baa8-11e8-97c6-9840bb29ab05'), max_length=64, verbose_name='Activation key'),
        ),
    ]
