# Generated by Django 2.1 on 2018-09-17 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20180918_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('f1f3f0ca-baa8-11e8-992e-9840bb29ab05'), max_length=64, verbose_name='Activation key'),
        ),
    ]
