# Generated by Django 2.1 on 2018-09-17 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20180918_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('79b711b6-baae-11e8-b187-9840bb29ab05'), max_length=64, verbose_name='Activation key'),
        ),
    ]
