# Generated by Django 2.1 on 2018-09-18 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0007_auto_20180918_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('1a0b7cdc-bb5c-11e8-b13c-9840bb29ab05'), max_length=64, verbose_name='Activation key'),
        ),
    ]
