# Generated by Django 2.1 on 2018-09-19 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_auto_20180918_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('59d20036-bc26-11e8-afcc-9840bb29ab05'), max_length=64, verbose_name='Activation key'),
        ),
    ]
