# Generated by Django 2.1 on 2018-09-28 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0011_auto_20180927_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('4f91eba8-c311-11e8-a47e-28565aa2d5fc'), max_length=64, verbose_name='Activation key'),
        ),
    ]
