# Generated by Django 2.1 on 2018-09-28 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0012_auto_20180928_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('f539f9c2-c322-11e8-bf1d-28565aa2d5fc'), max_length=64, verbose_name='Activation key'),
        ),
    ]
