# Generated by Django 2.1 on 2018-09-29 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0013_auto_20180928_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('b84c9a00-c386-11e8-b65b-28565aa2d5fc'), max_length=64, verbose_name='Activation key'),
        ),
    ]
