# Generated by Django 2.1 on 2018-09-29 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0014_auto_20180929_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('dd4e40f0-c386-11e8-84fb-28565aa2d5fc'), max_length=64, verbose_name='Activation key'),
        ),
    ]
