# Generated by Django 2.1 on 2018-09-29 01:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0015_auto_20180929_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('10c1515e-c388-11e8-b95e-28565aa2d5fc'), max_length=64, verbose_name='Activation key'),
        ),
    ]
