# Generated by Django 2.1 on 2018-09-29 01:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0016_auto_20180929_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(default=uuid.UUID('bc560f28-c38a-11e8-a3d8-28565aa2d5fc'), max_length=64, verbose_name='Activation key'),
        ),
    ]
