# Generated by Django 2.1 on 2018-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incubators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('city_location', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('logo', models.FileField(upload_to='')),
                ('verify', models.BooleanField(default=False)),
                ('latt', models.FloatField(default=30)),
                ('lonn', models.FloatField(default=25)),
            ],
        ),
    ]
