# Generated by Django 2.1 on 2018-09-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incubators',
            new_name='Emarket',
        ),
    ]
