# Generated by Django 2.1 on 2018-09-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180918_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_img', models.FileField(upload_to='')),
                ('shop_contact', models.CharField(default='Enter all means to contact.', max_length=600)),
                ('shop_details', models.TextField(max_length=2500)),
                ('shop_address', models.TextField(default='Address', max_length=600)),
                ('shop_doc', models.FileField(upload_to='')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banana_pudding', to='main.Emarket')),
            ],
        ),
    ]
