# Generated by Django 2.1 on 2018-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=2500)),
            ],
        ),
    ]
