# Generated by Django 2.1 on 2018-09-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_plantation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
