# Generated by Django 2.1 on 2018-09-27 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_discover'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=25)),
                ('passage', models.TextField(max_length=2500)),
                ('video', models.CharField(max_length=100)),
                ('innov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banana_pudding', to='main.Discover')),
            ],
        ),
    ]
