# Generated by Django 2.1 on 2018-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_discdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(default='Enter phone number.', max_length=100)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
