# Generated by Django 2.1 on 2018-09-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_discdetails_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='discover',
            name='rid2',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
