# Generated by Django 2.1 on 2018-09-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180929_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discdetails',
            name='innov',
        ),
        migrations.DeleteModel(
            name='DiscDetails',
        ),
        migrations.DeleteModel(
            name='Discover',
        ),
    ]
